// Search names for the 177 country polygons the globe draws (Natural Earth names, which is what
// a click sends). `common` is what people call the place when they put a webcam online — search
// for "Iran", not "Islamic Republic of Iran". `city` is where public webcams are likeliest: the
// capital, unless a bigger or more-visited city clearly has more (Istanbul, Sydney, Rio…).
// `camera: false` marks places with no public webcam infrastructure worth a paid search; the
// ladder still checks the channel's own cache for them, but doesn't spend Firecrawl credit.
export type Geo = { common: string; city: string; camera?: false };

export const GEO: Record<string, Geo> = {
  Fiji: { common: "Fiji", city: "Suva" },
  "United Republic of Tanzania": { common: "Tanzania", city: "Dar es Salaam" },
  "Western Sahara": { common: "Western Sahara", city: "Laayoune" },
  Canada: { common: "Canada", city: "Toronto" },
  "United States of America": { common: "United States", city: "New York" },
  Kazakhstan: { common: "Kazakhstan", city: "Almaty" },
  Uzbekistan: { common: "Uzbekistan", city: "Tashkent" },
  "Papua New Guinea": { common: "Papua New Guinea", city: "Port Moresby" },
  Indonesia: { common: "Indonesia", city: "Bali" },
  Argentina: { common: "Argentina", city: "Buenos Aires" },
  Chile: { common: "Chile", city: "Santiago" },
  "Democratic Republic of the Congo": { common: "DR Congo", city: "Kinshasa" },
  Somalia: { common: "Somalia", city: "Mogadishu" },
  Kenya: { common: "Kenya", city: "Nairobi" },
  Sudan: { common: "Sudan", city: "Khartoum" },
  Chad: { common: "Chad", city: "N'Djamena" },
  Haiti: { common: "Haiti", city: "Port-au-Prince" },
  "Dominican Republic": { common: "Dominican Republic", city: "Punta Cana" },
  "Russian Federation": { common: "Russia", city: "Moscow" },
  Bahamas: { common: "Bahamas", city: "Nassau" },
  "Falkland Islands (Malvinas)": { common: "Falkland Islands", city: "Stanley" },
  Norway: { common: "Norway", city: "Oslo" },
  Greenland: { common: "Greenland", city: "Nuuk" },
  "French Southern Territories": { common: "Kerguelen Islands", city: "Port-aux-Français", camera: false },
  "Timor-Leste": { common: "Timor-Leste", city: "Dili" },
  "South Africa": { common: "South Africa", city: "Cape Town" },
  Lesotho: { common: "Lesotho", city: "Maseru" },
  Mexico: { common: "Mexico", city: "Mexico City" },
  Uruguay: { common: "Uruguay", city: "Montevideo" },
  Brazil: { common: "Brazil", city: "Rio de Janeiro" },
  Bolivia: { common: "Bolivia", city: "La Paz" },
  Peru: { common: "Peru", city: "Lima" },
  Colombia: { common: "Colombia", city: "Bogotá" },
  Panama: { common: "Panama", city: "Panama City" },
  "Costa Rica": { common: "Costa Rica", city: "San José" },
  Nicaragua: { common: "Nicaragua", city: "Managua" },
  Honduras: { common: "Honduras", city: "Tegucigalpa" },
  "El Salvador": { common: "El Salvador", city: "San Salvador" },
  Guatemala: { common: "Guatemala", city: "Antigua Guatemala" },
  Belize: { common: "Belize", city: "San Pedro" },
  Venezuela: { common: "Venezuela", city: "Caracas" },
  Guyana: { common: "Guyana", city: "Georgetown" },
  Suriname: { common: "Suriname", city: "Paramaribo" },
  France: { common: "France", city: "Paris" },
  Ecuador: { common: "Ecuador", city: "Quito" },
  "Puerto Rico": { common: "Puerto Rico", city: "San Juan" },
  Jamaica: { common: "Jamaica", city: "Montego Bay" },
  Cuba: { common: "Cuba", city: "Havana" },
  Zimbabwe: { common: "Zimbabwe", city: "Victoria Falls" },
  Botswana: { common: "Botswana", city: "Gaborone" },
  Namibia: { common: "Namibia", city: "Windhoek" },
  Senegal: { common: "Senegal", city: "Dakar" },
  Mali: { common: "Mali", city: "Bamako" },
  Mauritania: { common: "Mauritania", city: "Nouakchott" },
  Benin: { common: "Benin", city: "Cotonou" },
  Niger: { common: "Niger", city: "Niamey" },
  Nigeria: { common: "Nigeria", city: "Lagos" },
  Cameroon: { common: "Cameroon", city: "Douala" },
  Togo: { common: "Togo", city: "Lomé" },
  Ghana: { common: "Ghana", city: "Accra" },
  "Cote d'Ivoire": { common: "Ivory Coast", city: "Abidjan" },
  Guinea: { common: "Guinea", city: "Conakry" },
  "Guinea-Bissau": { common: "Guinea-Bissau", city: "Bissau" },
  Liberia: { common: "Liberia", city: "Monrovia" },
  "Sierra Leone": { common: "Sierra Leone", city: "Freetown" },
  "Burkina Faso": { common: "Burkina Faso", city: "Ouagadougou" },
  "Central African Republic": { common: "Central African Republic", city: "Bangui" },
  "Republic of the Congo": { common: "Republic of the Congo", city: "Brazzaville" },
  Gabon: { common: "Gabon", city: "Libreville" },
  "Equatorial Guinea": { common: "Equatorial Guinea", city: "Malabo" },
  Zambia: { common: "Zambia", city: "Lusaka" },
  Malawi: { common: "Malawi", city: "Lilongwe" },
  Mozambique: { common: "Mozambique", city: "Maputo" },
  Eswatini: { common: "Eswatini", city: "Mbabane" },
  Angola: { common: "Angola", city: "Luanda" },
  Burundi: { common: "Burundi", city: "Bujumbura" },
  Israel: { common: "Israel", city: "Tel Aviv" },
  Lebanon: { common: "Lebanon", city: "Beirut" },
  Madagascar: { common: "Madagascar", city: "Antananarivo" },
  "State of Palestine": { common: "Palestine", city: "Ramallah" },
  "Republic of The Gambia": { common: "The Gambia", city: "Banjul" },
  Tunisia: { common: "Tunisia", city: "Tunis" },
  Algeria: { common: "Algeria", city: "Algiers" },
  Jordan: { common: "Jordan", city: "Amman" },
  "United Arab Emirates": { common: "United Arab Emirates", city: "Dubai" },
  Qatar: { common: "Qatar", city: "Doha" },
  Kuwait: { common: "Kuwait", city: "Kuwait City" },
  Iraq: { common: "Iraq", city: "Baghdad" },
  Oman: { common: "Oman", city: "Muscat" },
  Vanuatu: { common: "Vanuatu", city: "Port Vila" },
  Cambodia: { common: "Cambodia", city: "Phnom Penh" },
  Thailand: { common: "Thailand", city: "Bangkok" },
  "Lao People's Democratic Republic": { common: "Laos", city: "Vientiane" },
  Myanmar: { common: "Myanmar", city: "Yangon" },
  Vietnam: { common: "Vietnam", city: "Ho Chi Minh City" },
  "North Korea": { common: "North Korea", city: "Pyongyang" },
  "South Korea": { common: "South Korea", city: "Seoul" },
  Mongolia: { common: "Mongolia", city: "Ulaanbaatar" },
  India: { common: "India", city: "Mumbai" },
  Bangladesh: { common: "Bangladesh", city: "Dhaka" },
  Bhutan: { common: "Bhutan", city: "Thimphu" },
  Nepal: { common: "Nepal", city: "Kathmandu" },
  Pakistan: { common: "Pakistan", city: "Karachi" },
  Afghanistan: { common: "Afghanistan", city: "Kabul" },
  Tajikistan: { common: "Tajikistan", city: "Dushanbe" },
  Kyrgyzstan: { common: "Kyrgyzstan", city: "Bishkek" },
  Turkmenistan: { common: "Turkmenistan", city: "Ashgabat" },
  "Islamic Republic of Iran": { common: "Iran", city: "Tehran" },
  "Syrian Arab Republic": { common: "Syria", city: "Damascus" },
  Armenia: { common: "Armenia", city: "Yerevan" },
  Sweden: { common: "Sweden", city: "Stockholm" },
  Belarus: { common: "Belarus", city: "Minsk" },
  Ukraine: { common: "Ukraine", city: "Kyiv" },
  Poland: { common: "Poland", city: "Kraków" },
  Austria: { common: "Austria", city: "Vienna" },
  Hungary: { common: "Hungary", city: "Budapest" },
  "Moldova, Republic of": { common: "Moldova", city: "Chișinău" },
  Romania: { common: "Romania", city: "Bucharest" },
  Lithuania: { common: "Lithuania", city: "Vilnius" },
  Latvia: { common: "Latvia", city: "Riga" },
  Estonia: { common: "Estonia", city: "Tallinn" },
  Germany: { common: "Germany", city: "Berlin" },
  Bulgaria: { common: "Bulgaria", city: "Sofia" },
  Greece: { common: "Greece", city: "Athens" },
  Türkiye: { common: "Turkey", city: "Istanbul" },
  Albania: { common: "Albania", city: "Tirana" },
  Croatia: { common: "Croatia", city: "Dubrovnik" },
  Switzerland: { common: "Switzerland", city: "Zermatt" },
  Luxembourg: { common: "Luxembourg", city: "Luxembourg City" },
  Belgium: { common: "Belgium", city: "Brussels" },
  Netherlands: { common: "Netherlands", city: "Amsterdam" },
  Portugal: { common: "Portugal", city: "Lisbon" },
  Spain: { common: "Spain", city: "Barcelona" },
  Ireland: { common: "Ireland", city: "Dublin" },
  "New Caledonia": { common: "New Caledonia", city: "Nouméa" },
  "Solomon Islands": { common: "Solomon Islands", city: "Honiara" },
  "New Zealand": { common: "New Zealand", city: "Queenstown" },
  Australia: { common: "Australia", city: "Sydney" },
  "Sri Lanka": { common: "Sri Lanka", city: "Colombo" },
  "People's Republic of China": { common: "China", city: "Shanghai" },
  "Taiwan, Province of China": { common: "Taiwan", city: "Taipei" },
  Italy: { common: "Italy", city: "Venice" },
  Denmark: { common: "Denmark", city: "Copenhagen" },
  "United Kingdom": { common: "United Kingdom", city: "London" },
  Iceland: { common: "Iceland", city: "Reykjavík" },
  Azerbaijan: { common: "Azerbaijan", city: "Baku" },
  Georgia: { common: "Georgia", city: "Tbilisi" },
  Philippines: { common: "Philippines", city: "Manila" },
  Malaysia: { common: "Malaysia", city: "Kuala Lumpur" },
  "Brunei Darussalam": { common: "Brunei", city: "Bandar Seri Begawan" },
  Slovenia: { common: "Slovenia", city: "Ljubljana" },
  Finland: { common: "Finland", city: "Helsinki" },
  Slovakia: { common: "Slovakia", city: "Bratislava" },
  "Czech Republic": { common: "Czech Republic", city: "Prague" },
  Eritrea: { common: "Eritrea", city: "Asmara" },
  Japan: { common: "Japan", city: "Tokyo" },
  Paraguay: { common: "Paraguay", city: "Asunción" },
  Yemen: { common: "Yemen", city: "Sanaa" },
  "Saudi Arabia": { common: "Saudi Arabia", city: "Mecca" },
  Antarctica: { common: "Antarctica", city: "McMurdo Station" },
  "N. Cyprus": { common: "Northern Cyprus", city: "Kyrenia" },
  Cyprus: { common: "Cyprus", city: "Limassol" },
  Morocco: { common: "Morocco", city: "Marrakech" },
  Egypt: { common: "Egypt", city: "Cairo" },
  Libya: { common: "Libya", city: "Tripoli" },
  Ethiopia: { common: "Ethiopia", city: "Addis Ababa" },
  Djibouti: { common: "Djibouti", city: "Djibouti City" },
  Somaliland: { common: "Somaliland", city: "Hargeisa" },
  Uganda: { common: "Uganda", city: "Kampala" },
  Rwanda: { common: "Rwanda", city: "Kigali" },
  "Bosnia and Herzegovina": { common: "Bosnia and Herzegovina", city: "Sarajevo" },
  "The Republic of North Macedonia": { common: "North Macedonia", city: "Ohrid" },
  Serbia: { common: "Serbia", city: "Belgrade" },
  Montenegro: { common: "Montenegro", city: "Kotor" },
  Kosovo: { common: "Kosovo", city: "Pristina" },
  "Trinidad and Tobago": { common: "Trinidad and Tobago", city: "Port of Spain" },
  "South Sudan": { common: "South Sudan", city: "Juba" },
};

/** Every polygon we hold a search name for — what the coverage sweep walks. Countries marked
 *  `camera: false` stay in the list and are skipped by the sweep itself, so the reason they are
 *  excluded lives in one place. */
export const COUNTRY_NAMES: string[] = Object.keys(GEO);

/** Search names for a clicked country, falling back to the polygon's own name. */
export function geoFor(country: string): Geo {
  return GEO[country] ?? { common: country, city: country };
}

// The channel's own cameras carry short country names; the globe's polygons carry Natural
// Earth's. The few that differ, so a pool frame can answer a click on its polygon.
const ALIASES: Record<string, string> = { USA: "United States of America", "United States": "United States of America", UK: "United Kingdom", Taiwan: "Taiwan, Province of China" };

/** The polygon name for any country spelling we hold (a camera's, a common name, the polygon's own). */
export function polygonName(country: string): string {
  if (GEO[country]) return country;
  if (ALIASES[country]) return ALIASES[country];
  const hit = Object.entries(GEO).find(([, g]) => g.common === country);
  return hit ? hit[0] : country;
}
